const DATA = [
    {
        id:'DAT0001',
        title: "Lập Trình Không Khó",
        level: "Dễ",
        SumSubmited: "0",
        content: "Bài tập này giúp bạn làm quen với hệ thống Luyện Code Online của chúng tôi. Và cũng là bài tập thể hiện quyết tâm học lập trình của bạn! Tương truyền rằng những ai dám nói Lập Trình Không Khó là người đó sẽ gặt hái những thành công vang dội và viết lên những sản phẩm để đời.Do đó, yêu cầu của bài tập hết sức đơn giản. Công việc bạn cần phải làm là in ra câu nói: Lap Trinh Khong Kho!",
        inp: "",
        inpview: "Không có dữ liệu đầu vào!",
        out: `Lap Trinh Khong Kho!`,
        outview:`Lap Trinh Khong Kho!`,
    },
    {
        id:'DAT0002',
        title: "Tính tổng 2 số nguyên",
        level: "Dễ",
        SumSubmited: "0",
        content: "Viết chương trình cho phép nhập số nguyên a và b từ bàn phím. Tính và in kết quả a+b",
        inp: "1 2",
        inpview:"2 số nguyên a và b cách nhau 1 dấu cách",
        out: "3",
        outview:"Tổng của a và  b",
    },
    {
        id:'DAT0003',
        title: "Tính tổng, hiệu, tích, thương của 2 số nguyên",
        level: "Dễ",
        SumSubmited: "0",
        content: "Viết chương trình cho phép nhập vào 2 số nguyên aa và bb. Tính và in ra tổng a + b, hiệu a - b, tích a * b và thương a / b.",
        inp: "5 2",
        inpview:"Hai số nguyên a và b cách nhau bởi khoảng trắng",
        out: "7 3 10 2",
        outview:"4 giá trị tương ứng của 4 phép toán. Mỗi giá trị trên 1 dòng:Dòng 1: Kết quả của a + ba</br>&nbsp&nbspDòng 2: Kết quả của a - b</br>&nbsp&nbspDòng 3: Kết quả của  a * b</br>&nbsp&nbspDòng 4: Kết quả của a / b",
    },
    {
        id:'DAT0004',
        title: "Tìm số dư",
        level: "Dễ",
        SumSubmited: "0",
        content: "Viết chương trình nhập vào 2 số nguyên aa và bb. Tìm và in ra phần dư của phép toán a / b.",
        inp: "5 2",
        inpview:"2 số nguyên a và b cách nhau bởi khoảng trắng",
        out: "1",
        outview:"Giá trị dư của phép toán a / b",
    },
    {
        id:'DAT0005',
        title: "Tính chu vi, diện tích hình chữ nhật",
        level: "Dễ",
        SumSubmited: "0",
        content: "Viết chương trình tính và in ra chu vi, diện tích của hình chữ nhật cho biết trước chiều dài (d) và chiều rộng (r)",
        inp: "20 10",
        inpview:"2 giá trị cách nhau bởi khoảng trắng tương ứng là chiều dài và chiều rộng của hình chữ nhật.",
        out: "60200",
        outview:"Lần lượt là chu vi và diện tích của hình chữ nhật, mỗi kết quả trên 1 dòng.",
    },
    {
        id:'DAT0006',
        title: "Tính giai thừa 1",
        level: "Dễ",
        SumSubmited: "0",
        content: "Giai thừa là một toán tử 1 ngôi áp dụng cho các số tự nhiên. Giai thừa của 1 số tự nhiên nn được tính theo công thức sau: n!=1∗2∗...∗n.<br><br> Nhiệm vụ của bạn là viết chương trình tính giai thừa của 1 số n. ",
        inp: "4",
        inpview:"Số tự nhiên nn",
        out: "24",
        outview:"Giai thừa của số nn",
    },
    {
        id:'DAT0007',
        title: "Tính tổng các số chẵn trong [a, b]",
        level: "Dễ",
        SumSubmited: "0",
        content: "Nhập vào 2 số nguyên a và b, viết chương trình tính và in ra tổng của các số chẵn trong [a,b].",
        inp: "2 4",
        inpview:"Hai số nguyên a và b",
        out: "6",
        outview:"Tổng các số chẵn trong đoạn [a,b].",
    },
    {
        id:'DAT0008',
        title: "Tìm số lớn nhất",
        level: "Dễ",
        SumSubmited: "0",
        content: "Viết chương trình tìm số lớn nhất trong 2 số nguyên nhập từ bàn phím",
        inp: "1 5",
        inpview:"2 số nguyên cách nhau bởi khoảng trắng",
        out: "5",
        outview:"Số lớn nhất trong 2 số",
    },
    {
        id:'DAT0009',
        title: "Kiểm tra số nguyên tố",
        level: "Dễ",
        SumSubmited: "0",
        content: "Cho số nguyên N, hãy viết chương trình kiểm tra xem N có phải số nguyên tố hay không?",
        inp: "7",
        inpview:"Số nguyên N cần kiểm tra",
        out: "YES",
        outview:"Nếu N là số nguyên tố, in ra YES, ngược lại in ra NO",
    },
    {
        id:'DAT0010',
        title: "Liệt kê các ước số",
        level: "Dễ",
        SumSubmited: "0",
        content: "Viết chương trình liệt kê các ước nguyên dương của số nguyên n nhập từ bàn phím theo thứ tự giảm dần.",
        inp: "8",
        inpview:"Số nguyên n",
        out: "8 4 2 1 ",
        outview:"Danh sách các ước số nguyên dương của số nn theo thứ tự giảm dần, các số cách nhau bởi 1 dấu cách.",
    },
]
// .concat................