const DATA = [
    {
        // tam ví dụ 1 cái đi, mấy cái sau e chỉnh sau
        id:'Dat1',//nhớ là id luôn là cái duy nhất nhé, ngôn ngữ nào cx thế
        title: "Lập Trình Không Khó",
        level: "Dễ",
        SumSubmited: "0",
        content: "Bài tập này giúp bạn làm quen với hệ thống Luyện Code Online của chúng tôi. Và cũng là bài tập thể hiện quyết tâm học lập trình của bạn! Tương truyền rằng những ai dám nói Lập Trình Không Khó là người đó sẽ gặt hái những thành công vang dội và viết lên những sản phẩm để đời.Do đó, yêu cầu của bài tập hết sức đơn giản. Công việc bạn cần phải làm là in ra câu nói: Lap Trinh Khong Kho!",
        inp: "",
        inpview: "Không có dữ liệu đầu vào!",
        out: `Lap Trinh Khong Kho!`,
        outview:`Lap Trinh Khong Kho!`,
    },
    {
        id:'Dat2',
        title: "Tính tổng 2 số nguyên",
        level: "Dễ",
        SumSubmited: "0",
        content: "Viết chương trình cho phép nhập số nguyên a và b từ bàn phím. Tính và in kết quả a+b",
        inp: "1 2",
        inpview:"2 số nguyên a và b cách nhau 1 dấu cách",
        out: "3",
        outview:"Tổng của a và  b",
    },
    {
        id:'Dat3',
        title: "Tính tổng, hiệu, tích, thương của 2 số nguyên",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
    {
        id:'Dat4',
        title: "Tìm số dư",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
    {
        id:'Dat5',
        title: "Tính chu vi, diện tích hình chữ nhật",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
    {
        id:'Dat6',
        title: "Tính giai thừa 1",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
    {
        id:'Dat7',
        title: "Tính tổng các số chẵn trong [a, b]",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
    {
        id:'Dat8',
        title: "Tính S = x + x^2/2! + ... + x^n/n!",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
    {
        id:'Dat9',
        title: "Kiểm tra số nguyên tố",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
    {
        id:'Dat10',
        title: "Liệt kê các ước số",
        level: "Dễ",
        SumSubmited: "0",
        content: "",
        inp: "",
        inpview:"",
        out: "",
        outview:"",
    },
]
